### ISSUE TITLE
pnpm-deduplicate doesn't work on node.js v18

### ISSUE THREAD

**Issue by ocavue** [ocavue/pnpm-deduplicate#2]
```
$ node --version 
v18.6.0
$ pnpm-deduplicate --help
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/equals.js' is not defined by "exports" in /private/tmp/test-pnpm-deduplicate/node_modules/.pnpm/@pnpm+lockfile-file@5.3.1_@pnpm+logger@4.0.0/node_modules/ramda/package.json
```

Caused by this issue: https://github.com/ramda/ramda/issues/3281

**Comment by JoshuaKGoldberg** [comment]
Note: this works on my CI. https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/74 -> https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/3624721655/jobs/6112004599.

* Node version: v18.7.0
* pnpm version: @7.16.0

**Comment by ocavue** [comment]
Indeed, I cannot reproduce this issue anymore with Node 18. I added CI to this project so that I can test case thing easier in the future. Thank you for letting me know that.
