### ISSUE TITLE
Link to the GitHub in package.json

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ocavue/pnpm-deduplicate#5]
Hi, I just discovered this through https://github.com/pnpm/pnpm/discussions/4143 - great tool! Thanks for making it!

https://www.npmjs.com/package/pnpm-deduplicate doesn't have a link to this GitHub repo though. It's because there's no [`package.json` `repository` field](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository). Would you mind me sending a PR to add it in?

**Comment by ocavue** [comment]
Go ahead. Thanks!
